// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.fzrilsh.toice

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * OS thermal state, normalized across platforms (ADR-003 thermal_score).
 * Maps ProcessInfo.thermalState (iOS) and PowerManager thermal status
 * (Android) onto a common ordinal.
 */
enum class ThermalState(val raw: Int) {
  NOMINAL(0),
  FAIR(1),
  SERIOUS(2),
  CRITICAL(3);

  companion object {
    fun ofRaw(raw: Int): ThermalState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * How the host AP was brought up (ADR-002 addendum).
 *
 * [programmatic]: app configured the SoftAp with the fixed credentials
 * (Android 13+ reflection path). [manualRequired]: the app could not set
 * credentials, so the user must configure the hotspot by hand in Settings.
 */
enum class HostStartMode(val raw: Int) {
  PROGRAMMATIC(0),
  MANUAL_REQUIRED(1);

  companion object {
    fun ofRaw(raw: Int): HostStartMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Fixed WiFi hotspot credentials shared for the life of a trip (ADR-002).
 * Reused by every subsequent host so iOS auto-rejoins without a new prompt.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HotspotCredentials (
  val ssid: String,
  val password: String,
  val groupId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HotspotCredentials {
      val ssid = pigeonVar_list[0] as String
      val password = pigeonVar_list[1] as String
      val groupId = pigeonVar_list[2] as String
      return HotspotCredentials(ssid, password, groupId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ssid,
      password,
      groupId,
    )
  }
}
private open class NativeBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ThermalState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HostStartMode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HotspotCredentials.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ThermalState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is HostStartMode -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is HotspotCredentials -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Hotspot host/join control (ADR-001, ADR-002). Android: custom
 * SoftApConfiguration via reflection, else manual fallback. iOS cannot host,
 * and joins via the system Camera WiFi-QR flow, not this API.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HotspotApi {
  fun startHost(credentials: HotspotCredentials, callback: (Result<HostStartMode>) -> Unit)
  fun stopHost(callback: (Result<Unit>) -> Unit)
  /** Open the OS tethering/hotspot settings for the manual fallback path. */
  fun openTetherSettings(callback: (Result<Unit>) -> Unit)
  fun joinAsClient(credentials: HotspotCredentials, callback: (Result<Unit>) -> Unit)
  fun leave(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by HotspotApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeBridgePigeonCodec()
    }
    /** Sets up an instance of `HotspotApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HotspotApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.HotspotApi.startHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as HotspotCredentials
            api.startHost(credentialsArg) { result: Result<HostStartMode> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.HotspotApi.stopHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopHost{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.HotspotApi.openTetherSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openTetherSettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.HotspotApi.joinAsClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as HotspotCredentials
            api.joinAsClient(credentialsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.HotspotApi.leave$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.leave{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Sensor reads feeding the ADR-003 fitness score.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SensorApi {
  /** Battery level 0-100. */
  fun getBatteryLevel(callback: (Result<Long>) -> Unit)
  fun getThermalState(callback: (Result<ThermalState>) -> Unit)
  /**
   * RSSI (dBm) to each connected peer, keyed by peer/group member id.
   * Used to derive the worst-case (minimum) RSSI for rssi_score.
   */
  fun getRssiToPeers(callback: (Result<Map<String, Long>>) -> Unit)

  companion object {
    /** The codec used by SensorApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeBridgePigeonCodec()
    }
    /** Sets up an instance of `SensorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SensorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.SensorApi.getBatteryLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBatteryLevel{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.SensorApi.getThermalState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getThermalState{ result: Result<ThermalState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.SensorApi.getRssiToPeers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRssiToPeers{ result: Result<Map<String, Long>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Keep-alive session control (ADR-005). Android: foreground service with
 * persistent notification. iOS: background audio session.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BackgroundApi {
  fun startForegroundSession(callback: (Result<Unit>) -> Unit)
  fun stopForegroundSession(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BackgroundApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeBridgePigeonCodec()
    }
    /** Sets up an instance of `BackgroundApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BackgroundApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.BackgroundApi.startForegroundSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startForegroundSession{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.toice.BackgroundApi.stopForegroundSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopForegroundSession{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart push channel for asynchronous hotspot state changes.
 * The host API is request/response only; the OS may tear the AP down or a
 * client link may drop out of band, so those arrive here.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class HotspotEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HotspotEvents. */
    val codec: MessageCodec<Any?> by lazy {
      NativeBridgePigeonCodec()
    }
  }
  /** The hosted AP stopped (OS shutdown, failure, or explicit stopHost). */
  fun onHostStopped(reasonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.toice.HotspotEvents.onHostStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(reasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** This device's client connection to the hotspot came up or went down. */
  fun onClientStateChanged(connectedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.toice.HotspotEvents.onClientStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(connectedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
