// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// OS thermal state, normalized across platforms (ADR-003 thermal_score).
/// Maps ProcessInfo.thermalState (iOS) and PowerManager thermal status
/// (Android) onto a common ordinal.
enum ThermalState: Int {
  case nominal = 0
  case fair = 1
  case serious = 2
  case critical = 3
}

/// How the host AP was brought up (ADR-002 addendum).
///
/// [programmatic]: app configured the SoftAp with the fixed credentials
/// (Android 13+ reflection path). [manualRequired]: the app could not set
/// credentials, so the user must configure the hotspot by hand in Settings.
enum HostStartMode: Int {
  case programmatic = 0
  case manualRequired = 1
}

/// Fixed WiFi hotspot credentials shared for the life of a trip (ADR-002).
/// Reused by every subsequent host so iOS auto-rejoins without a new prompt.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HotspotCredentials {
  var ssid: String
  var password: String
  var groupId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HotspotCredentials? {
    let ssid = pigeonVar_list[0] as! String
    let password = pigeonVar_list[1] as! String
    let groupId = pigeonVar_list[2] as! String

    return HotspotCredentials(
      ssid: ssid,
      password: password,
      groupId: groupId
    )
  }
  func toList() -> [Any?] {
    return [
      ssid,
      password,
      groupId,
    ]
  }
}

private class NativeBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HostStartMode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return HotspotCredentials.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ThermalState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HostStartMode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? HotspotCredentials {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeBridgePigeonCodecWriter(data: data)
  }
}

class NativeBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeBridgePigeonCodec(readerWriter: NativeBridgePigeonCodecReaderWriter())
}


/// Hotspot host/join control (ADR-001, ADR-002). Android: custom
/// SoftApConfiguration via reflection, else manual fallback. iOS cannot host,
/// and joins via the system Camera WiFi-QR flow, not this API.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HotspotApi {
  func startHost(credentials: HotspotCredentials, completion: @escaping (Result<HostStartMode, Error>) -> Void)
  func stopHost(completion: @escaping (Result<Void, Error>) -> Void)
  /// Open the OS tethering/hotspot settings for the manual fallback path.
  func openTetherSettings(completion: @escaping (Result<Void, Error>) -> Void)
  func joinAsClient(credentials: HotspotCredentials, completion: @escaping (Result<Void, Error>) -> Void)
  func leave(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HotspotApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeBridgePigeonCodec.shared }
  /// Sets up an instance of `HotspotApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HotspotApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startHostChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.HotspotApi.startHost\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startHostChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialsArg = args[0] as! HotspotCredentials
        api.startHost(credentials: credentialsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startHostChannel.setMessageHandler(nil)
    }
    let stopHostChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.HotspotApi.stopHost\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopHostChannel.setMessageHandler { _, reply in
        api.stopHost { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopHostChannel.setMessageHandler(nil)
    }
    /// Open the OS tethering/hotspot settings for the manual fallback path.
    let openTetherSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.HotspotApi.openTetherSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openTetherSettingsChannel.setMessageHandler { _, reply in
        api.openTetherSettings { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openTetherSettingsChannel.setMessageHandler(nil)
    }
    let joinAsClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.HotspotApi.joinAsClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      joinAsClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialsArg = args[0] as! HotspotCredentials
        api.joinAsClient(credentials: credentialsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      joinAsClientChannel.setMessageHandler(nil)
    }
    let leaveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.HotspotApi.leave\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      leaveChannel.setMessageHandler { _, reply in
        api.leave { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      leaveChannel.setMessageHandler(nil)
    }
  }
}
/// Sensor reads feeding the ADR-003 fitness score.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SensorApi {
  /// Battery level 0-100.
  func getBatteryLevel(completion: @escaping (Result<Int64, Error>) -> Void)
  func getThermalState(completion: @escaping (Result<ThermalState, Error>) -> Void)
  /// RSSI (dBm) to each connected peer, keyed by peer/group member id.
  /// Used to derive the worst-case (minimum) RSSI for rssi_score.
  func getRssiToPeers(completion: @escaping (Result<[String: Int64], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SensorApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeBridgePigeonCodec.shared }
  /// Sets up an instance of `SensorApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SensorApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Battery level 0-100.
    let getBatteryLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.SensorApi.getBatteryLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryLevelChannel.setMessageHandler { _, reply in
        api.getBatteryLevel { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBatteryLevelChannel.setMessageHandler(nil)
    }
    let getThermalStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.SensorApi.getThermalState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThermalStateChannel.setMessageHandler { _, reply in
        api.getThermalState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThermalStateChannel.setMessageHandler(nil)
    }
    /// RSSI (dBm) to each connected peer, keyed by peer/group member id.
    /// Used to derive the worst-case (minimum) RSSI for rssi_score.
    let getRssiToPeersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.SensorApi.getRssiToPeers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRssiToPeersChannel.setMessageHandler { _, reply in
        api.getRssiToPeers { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRssiToPeersChannel.setMessageHandler(nil)
    }
  }
}
/// Keep-alive session control (ADR-005). Android: foreground service with
/// persistent notification. iOS: background audio session.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackgroundApi {
  func startForegroundSession(completion: @escaping (Result<Void, Error>) -> Void)
  func stopForegroundSession(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackgroundApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeBridgePigeonCodec.shared }
  /// Sets up an instance of `BackgroundApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackgroundApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startForegroundSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.BackgroundApi.startForegroundSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startForegroundSessionChannel.setMessageHandler { _, reply in
        api.startForegroundSession { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startForegroundSessionChannel.setMessageHandler(nil)
    }
    let stopForegroundSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.toice.BackgroundApi.stopForegroundSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopForegroundSessionChannel.setMessageHandler { _, reply in
        api.stopForegroundSession { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopForegroundSessionChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Dart push channel for asynchronous hotspot state changes.
/// The host API is request/response only; the OS may tear the AP down or a
/// client link may drop out of band, so those arrive here.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HotspotEventsProtocol {
  /// The hosted AP stopped (OS shutdown, failure, or explicit stopHost).
  func onHostStopped(reason reasonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// This device's client connection to the hotspot came up or went down.
  func onClientStateChanged(connected connectedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class HotspotEvents: HotspotEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NativeBridgePigeonCodec {
    return NativeBridgePigeonCodec.shared
  }
  /// The hosted AP stopped (OS shutdown, failure, or explicit stopHost).
  func onHostStopped(reason reasonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.toice.HotspotEvents.onHostStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([reasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// This device's client connection to the hotspot came up or went down.
  func onClientStateChanged(connected connectedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.toice.HotspotEvents.onClientStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([connectedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
